import express from 'express';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {cards} from '../src/data/cards.js';
const app=express();
const __dirname=path.dirname(fileURLToPath(import.meta.url));
app.use(express.json());
app.get('/api/health',(req,res)=>res.json({ok:true,name:'Special Deck',version:'3.0.0'}));
app.get('/api/cards',(req,res)=>res.json({count:cards.length,cards}));
app.get('/api/cards/:id',(req,res)=>{const c=cards.find(x=>String(x.id)===req.params.id);if(!c)return res.status(404).json({error:'Card not found'});res.json(c)});
app.use(express.static(path.resolve(__dirname,'..')));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`Special Deck web server running on ${port}`));
