// Special Deck AI: collection-aware deck search with diversified batches.
const WIN = new Set(['Hog Rider','Giant','Royal Giant','Balloon','Wall Breakers','Royal Hogs','Goblin Barrel','X-Bow','Mortar','Ram Rider','Goblin Giant','Graveyard','Lava Hound','Golem','Electro Giant','Minion Giant','Ronin']);
const AIR = new Set(['Archers','Minions','Hunter','Magic Archer','Ice Wizard','Musketeer','Baby Dragon','Electro Wizard','Inferno Dragon','Mega Minion','Phoenix','Firecracker','Flying Machine','Minion Horde','Skeleton Dragons','Executioner','Princess','Little Prince','Archer Queen']);
const BUILDINGS = new Set(['Cannon','Tesla','Bomb Tower','Inferno Tower','Goblin Cage','Tombstone','Furnace','Goblin Hut','Barbarian Hut','Mortar','X-Bow','Elixir Collector']);
const CHEAP = new Set(['Skeletons','Goblins','Spear Goblins','Bats','Bomber','Zap','The Log','Giant Snowball','Rage','Barbarian Barrel','Mirror']);
const HEAVY = new Set(['Golem','Electro Giant','P.E.K.K.A','Mega Knight','Lava Hound','Three Musketeers','Royal Recruits','Goblin Giant','Minion Giant']);
const SPELLS = new Set(['Fireball','Arrows','Zap','Rocket','The Log','Poison','Lightning','Freeze','Tornado','Rage','Giant Snowball','Earthquake','Barbarian Barrel','Goblin Barrel','Graveyard','Mirror','Clone','Void','Vines']);
const role = c => ({win:WIN.has(c.name),air:AIR.has(c.name),building:BUILDINGS.has(c.name),cheap:CHEAP.has(c.name),heavy:HEAVY.has(c.name),spell:c.type==='Spell'||SPELLS.has(c.name),support:!WIN.has(c.name)&&!BUILDINGS.has(c.name)&&!CHEAP.has(c.name)&&!HEAVY.has(c.name)});
const weights={Balanced:{win:1.15,def:1.05,air:1.05,cycle:1,spell:1},Cycle:{win:1.15,def:.95,air:1,cycle:1.45,spell:1.05},Control:{win:1.1,def:1.35,air:1.2,cycle:1,spell:1.3},Beatdown:{win:1.45,def:1,air:1.2,cycle:.7,spell:1.05},BridgeSpam:{win:1.3,def:1.1,air:1.05,cycle:1.25,spell:1.1}};
const synergyPairs=new Map([
 ['Hog Rider|Earthquake',10],['Hog Rider|The Log',5],['Hog Rider|Firecracker',6],['Hog Rider|Cannon',5],['Miner|Wall Breakers',11],['Miner|Poison',7],['Miner|Bats',4],['Miner|Inferno Tower',3],['Graveyard|Poison',10],['Graveyard|Freeze',7],['Graveyard|Baby Dragon',6],['Graveyard|Tornado',4],['Lava Hound|Balloon',11],['Lava Hound|Inferno Dragon',6],['Lava Hound|Tombstone',4],['Balloon|Freeze',6],['Golem|Night Witch',10],['Golem|Baby Dragon',5],['Golem|Lightning',7],['Golem|Tornado',4],['Royal Giant|Fisherman',8],['Royal Giant|Lightning',7],['Royal Giant|Hunter',6],['Royal Giant|The Log',4],['X-Bow|Tesla',8],['X-Bow|Archers',5],['X-Bow|The Log',4],['Mortar|Miner',7],['Mortar|Archers',5],['Goblin Barrel|Princess',8],['Goblin Barrel|The Log',-4],['Goblin Barrel|Rocket',5],['Mega Knight|Miner',6],['Mega Knight|Wall Breakers',7],['Mega Knight|Bats',5],['P.E.K.K.A|Battle Ram',8],['P.E.K.K.A|Magic Archer',6],['Battle Ram|Bandit',7],['Bandit|Magic Archer',4],['Royal Hogs|Earthquake',9],['Royal Hogs|Firecracker',6],['Royal Hogs|Royal Recruits',5],['Electro Giant|Tornado',9],['Electro Giant|Lightning',7],['Electro Giant|Baby Dragon',5],['Giant|Prince',6],['Giant|Dark Prince',6],['Giant|Mini P.E.K.K.A',4],['Poison|The Log',3],['Fireball|The Log',4],['Zap|Inferno Dragon',5],['Tornado|Executioner',9],['Tornado|Baby Dragon',7],['Tornado|Magic Archer',6],['Knight|Archers',5],['Knight|The Log',3],['Valkyrie|Firecracker',6],['Valkyrie|Tornado',5],['Tesla|The Log',4],['Cannon|The Log',4],['Inferno Tower|Tornado',3]
]);
const pairKey=(a,b)=>a.name<b.name?`${a.name}|${b.name}`:`${b.name}|${a.name}`;
const pairScore=(a,b)=>synergyPairs.get(pairKey(a,b))||0;
function baseScore(c,style,owned){const w=weights[style]||weights.Balanced,r=role(c);let s=0;if(r.win)s+=24*w.win;if(r.air)s+=8*w.air;if(r.building)s+=12*w.def;if(r.spell)s+=7*w.spell;if(r.cheap)s+=7*w.cycle;if(r.heavy)s-=4/w.cycle;if(c.evolution)s+=4;if(c.hero||c.champion)s+=3;const o=owned?.[c.id];if(o?.level===16||o?.max)s+=18;else if(o?.level)s+=Math.min(10,o.level/2);s-=Math.max(0,c.elixir-4)*1.2;return s}
function deckScore(deck,style,owned){const w=weights[style]||weights.Balanced;let s=deck.reduce((t,c)=>t+baseScore(c,style,owned),0),win=0,air=0,build=0,spells=0,cheap=0,heavy=0,total=0;for(const c of deck){const r=role(c);win+=r.win;air+=r.air;build+=r.building;spells+=r.spell;cheap+=r.cheap;heavy+=r.heavy;total+=c.elixir}for(let i=0;i<deck.length;i++)for(let j=i+1;j<deck.length;j++)s+=pairScore(deck[i],deck[j]);const avg=total/8;if(win===0)s-=60;if(win>2)s-=20*(win-2);if(air<2)s-=24*(2-air);if(build>2)s-=12*(build-2);if(spells<2)s-=16*(2-spells);if(spells>3)s-=8*(spells-3);if(cheap<2)s-=14*(2-cheap);if(avg>4.7)s-=20*(avg-4.7);if(avg<2.6)s-=12*(2.6-avg);if(style==='Beatdown'&&heavy<2)s-=18;if(style==='Cycle'&&cheap<4)s-=20;if(style==='Control'&&build<1)s-=10;return s+w.cycle*cheap*2}
function searchCandidates(cards,owned,style){const max=cards.filter(c=>owned?.[c.id]?.max||owned?.[c.id]?.level===16);const pool=(max.length>=8?max:cards).filter(c=>c.type!=='Hero'&&c.clashRoyaleId).slice().sort((a,b)=>baseScore(b,style,owned)-baseScore(a,style,owned));const candidates=pool.slice(0,Math.min(60,pool.length));let beam=[[]];for(let slot=0;slot<8;slot++){const next=[];for(const deck of beam)for(const c of candidates){if(deck.some(x=>x.id===c.id))continue;const d=[...deck,c];next.push({deck:d,score:slot===7?deckScore(d,style,owned):deck.reduce((s,x)=>s+baseScore(x,style,owned),0)+baseScore(c,style,owned)+d.reduce((s,x)=>s+role(x).win,0)*5})}next.sort((a,b)=>b.score-a.score);const unique=[];const seen=new Set();for(const x of next){const k=x.deck.map(c=>c.id).sort((a,b)=>a-b).join(',');if(seen.has(k))continue;seen.add(k);unique.push(x);if(unique.length>180)break}beam=unique.map(x=>x.deck)}return beam.map(deck=>({deck,score:deckScore(deck,style,owned)})).sort((a,b)=>b.score-a.score)}
export function generateDecksAI(cards,owned,style='Balanced',limit=300){const all=searchCandidates(cards,owned,style);const out=[];const used=new Set();for(const x of all){const key=x.deck.map(c=>c.id).sort((a,b)=>a-b).join(',');if(used.has(key))continue;used.add(key);out.push({...x,score:Math.round(x.score)});if(out.length>=limit)break}return out}
export function generateDeckAI(cards,owned,style='Balanced'){return generateDecksAI(cards,owned,style,1)[0]?.deck||[]}
export function rankExternalDecks(external,cards,owned,style='Balanced',limit=300){const byId=new Map(cards.filter(c=>c.clashRoyaleId).map(c=>[c.clashRoyaleId,c]));const out=[];for(const item of external||[]){const deck=(item.deck||[]).map(x=>byId.get(x.id)).filter(Boolean);if(deck.length!==8)continue;const ownedCount=deck.filter(c=>owned?.[c.id]?.max||owned?.[c.id]?.level===16).length;const score=deckScore(deck,style,owned)+ownedCount*12;out.push({deck,score:Math.round(score),rank:item.rank||null,source:'Top Ladder'});}out.sort((a,b)=>b.score-a.score||((a.rank||9999)-(b.rank||9999)));return out.slice(0,limit)}
export function analyzeDeckAI(deck){if(!deck.length)return{synergy:0,coverage:0,balance:0,score:0};const roles=deck.map(role),win=roles.filter(r=>r.win).length,air=roles.filter(r=>r.air).length,buildings=roles.filter(r=>r.building).length,spells=roles.filter(r=>r.spell).length;let synergy=0;for(let i=0;i<deck.length;i++)for(let j=i+1;j<deck.length;j++)synergy+=pairScore(deck[i],deck[j]);const avg=deck.reduce((s,c)=>s+c.elixir,0)/deck.length;const coverage=Math.min(100,win*28+air*18+buildings*15+spells*12),balance=Math.max(0,100-Math.abs(avg-3.7)*22-Math.max(0,spells-3)*8-Math.max(0,1-win)*35);return{synergy:Math.min(100,Math.round(50+synergy*2)),coverage:Math.round(coverage),balance:Math.round(balance),score:Math.round((Math.min(100,50+synergy*2)+coverage+balance)/3)}}
const COUNTERS={'Hog Rider':['Cannon','Tesla','Bomb Tower','Tornado','Goblin Cage'],'Royal Hogs':['Bomb Tower','Valkyrie','Bowler','Fireball','The Log'],'Balloon':['Musketeer','Hunter','Tesla','Inferno Tower','Firecracker'],'Giant':['Inferno Tower','P.E.K.K.A','Mini P.E.K.K.A','Cannon'],'Golem':['Inferno Tower','P.E.K.K.A','Mini P.E.K.K.A','Inferno Dragon'],'Electro Giant':['Cannon','Tesla','Inferno Tower','P.E.K.K.A'],'Mega Knight':['P.E.K.K.A','Inferno Tower','Knight','Valkyrie'],'Goblin Barrel':['The Log','Arrows','Barbarian Barrel','Zap'],'Graveyard':['Poison','Valkyrie','Baby Dragon','Tornado'],'Lava Hound':['Musketeer','Hunter','Inferno Dragon','Tesla','Firecracker'],'X-Bow':['Tesla','Rocket','Lightning','P.E.K.K.A'],'Mortar':['Cannon','Tesla','Knight','Valkyrie'],'Wall Breakers':['Valkyrie','Bomb Tower','The Log','Barbarian Barrel'],'Ram Rider':['Cannon','Tesla','P.E.K.K.A','Tornado'],'Royal Giant':['Tesla','Cannon','Inferno Tower','Fisherman'],'Minion Giant':['Hunter','Inferno Tower','P.E.K.K.A','Tesla'],'Goblin Giant':['Mini P.E.K.K.A','P.E.K.K.A','Inferno Tower','Cannon']};
export function analyzeMatchups(deck=[],opponent=[]){const enemyNames=new Set(opponent.map(c=>c.name));const countered=opponent.filter(c=>COUNTERS[c.name]);let coverage=0,gaps=[];for(const enemy of countered){const list=COUNTERS[enemy.name]||[];const found=deck.filter(c=>list.includes(c.name)).length;coverage+=found?1:0;if(!found)gaps.push(enemy.name)}const score=countered.length?Math.round(100*coverage/countered.length):50;const suggested=opponent.flatMap(c=>COUNTERS[c.name]||[]).filter((n,i,a)=>a.indexOf(n)===i).filter(n=>!enemyNames.has(n)).map(name=>deck.find(c=>c.name===name)||{name});return{score,gaps,suggested,threats:deck.filter(c=>COUNTERS[c.name]).map(c=>c.name)}}
export function findDeckWeaknesses(deck=[]){const r=deck.map(role),avg=deck.length?deck.reduce((s,c)=>s+c.elixir,0)/deck.length:0,weaknesses=[];if(!r.some(x=>x.win))weaknesses.push({key:'win',title:'No Win Condition',detail:'Add a reliable way to damage the enemy tower.'});if(r.filter(x=>x.air).length<2)weaknesses.push({key:'air',title:'Light Air Defense',detail:'Add another reliable anti-air card.'});if(r.filter(x=>x.building).length===0)weaknesses.push({key:'building',title:'No Defensive Building',detail:'Consider a building or a strong defensive unit.'});if(r.filter(x=>x.spell).length<2)weaknesses.push({key:'spell',title:'Low Spell Coverage',detail:'Two spells often give broader utility across matchups.'});if(avg>4.6)weaknesses.push({key:'elixir',title:'Heavy Elixir',detail:`Average elixir is ${avg.toFixed(1)}; consider a cheaper cycle/support card.`});if(avg<2.7)weaknesses.push({key:'light',title:'Very Fast Cycle',detail:`Average elixir is ${avg.toFixed(1)}; make sure the deck has enough stopping power.`});if(r.filter(x=>x.win).length>2)weaknesses.push({key:'wins',title:'Too Many Win Conditions',detail:'Trim redundant win conditions for stronger role coverage.'});return weaknesses}
export function suggestReplacements(deck,cards,owned,style='Balanced'){const weak=findDeckWeaknesses(deck);if(!weak.length)return[];const candidates=cards.filter(c=>!deck.some(x=>x.id===c.id)&&c.type!=='Hero').sort((a,b)=>baseScore(b,style,owned)-baseScore(a,style,owned));return weak.slice(0,3).map((w,i)=>({weakness:w,replacement:candidates[i]||candidates[0]})).filter(x=>x.replacement)}
