import React,{useEffect,useMemo,useState}from'react';
import{createRoot}from'react-dom/client';
import{loadCards}from'./data/cards';
import{generateDeckAI,analyzeDeckAI,analyzeMatchups,findDeckWeaknesses,suggestReplacements}from'./deck-ai';
import{META_DECKS,resolveMetaDeck}from'./meta-decks';
import'./style.css';
import{loadAccount,registerAccount,loginAccount,loadCloud,syncCloud,logoutAccount}from'./account';

const roleMap={'Hog Rider':'Win Condition','Giant':'Win Condition','Royal Giant':'Win Condition','Balloon':'Win Condition','Wall Breakers':'Win Condition','Royal Hogs':'Win Condition','Goblin Barrel':'Win Condition','X-Bow':'Win Condition','Mortar':'Win Condition','Ram Rider':'Win Condition','Goblin Giant':'Win Condition','Graveyard':'Win Condition','Lava Hound':'Win Condition','Golem':'Win Condition','Electro Giant':'Win Condition','Minion Giant':'Win Condition','Ronin':'Win Condition','P.E.K.K.A':'Tank Killer','Mega Knight':'Tank / Defense','Knight':'Mini Tank','Archers':'Air Defense','Minions':'Air Defense','Hunter':'Air Defense','Magic Archer':'Support','Ice Wizard':'Air Defense Support','Fireball':'Medium Spell','The Log':'Small Spell','Zap':'Small Spell','Poison':'Control Spell','Tornado':'Control Spell','Cannon':'Building','Tesla':'Building','Inferno Tower':'Building','Bomb Tower':'Building','Elixir Collector':'Economy'};
const STORAGE='special-deck-state-v3';
const role=c=>roleMap[c.name]||(c.type==='Building'?'Building':c.type==='Spell'?'Spell':c.type==='Hero'?'Hero Support':'Support');
const link=deck=>{const ids=deck.map(c=>c.clashRoyaleId).filter(Boolean);if(ids.length!==8)return null;return`https://link.clashroyale.com/deck/en?deck=${ids.join(';')}`};
const initials=n=>n.split(/\s+/).map(x=>x[0]).slice(0,2).join('');
function Metric({name,value}){return <div className="metric"><div><span>{name}</span><b>{value}</b></div><div className="bar"><i style={{width:`${value}%`}}/></div></div>}
const analyze=deck=>{const wins=deck.filter(c=>roleMap[c.name]==='Win Condition').length;const spells=deck.filter(c=>c.type==='Spell').length;const air=deck.filter(c=>['Air Defense','Air Defense Support'].includes(role(c))||['Archers','Musketeer','Hunter','Magic Archer','Baby Dragon','Electro Wizard','Inferno Dragon','Mega Minion','Phoenix','Firecracker','Flying Machine','Minion Horde','Skeleton Dragons','Executioner','Princess'].includes(c.name)).length;const defense=deck.filter(c=>['Building','Tank Killer','Mini Tank','Tank / Defense'].includes(role(c))).length;const cheap=deck.filter(c=>c.elixir<=3).length;return{wins,spells,attack:Math.min(100,wins*28+Math.min(20,deck.filter(c=>c.elixir>=4).length*4)),defense:Math.min(100,defense*22+air*12+spells*8),air:Math.min(100,air*28),cycle:Math.min(100,cheap*16+Math.max(0,4-(deck.reduce((s,c)=>s+c.elixir,0)/(deck.length||1)))*15)}};
function App(){
 const[cards,setCards]=useState([]),[owned,setOwned]=useState({}),[deck,setDeck]=useState([]),[query,setQuery]=useState(''),[rarity,setRarity]=useState('All'),[style,setStyle]=useState('Balanced'),[tab,setTab]=useState('builder'),[saved,setSaved]=useState([]),[notice,setNotice]=useState(''),[opponent,setOpponent]=useState([]),[account,setAccount]=useState(null),[authMode,setAuthMode]=useState('login'),[authName,setAuthName]=useState(''),[authEmail,setAuthEmail]=useState(''),[authPassword,setAuthPassword]=useState(''),[accountNotice,setAccountNotice]=useState('');
 useEffect(()=>{loadCards().then(setCards);try{const x=JSON.parse(localStorage.getItem(STORAGE)||'{}');setOwned(x.owned||{});setSaved(x.saved||[])}catch{}const a=loadAccount();setAccount(a);if(a)loadCloud().then(d=>{setOwned(d.owned||{});setSaved(d.saved||[]);localStorage.setItem(STORAGE,JSON.stringify({owned:d.owned||{},saved:d.saved||[]}));setAccountNotice('Cloud data synced.')}).catch(()=>setAccountNotice('Signed in locally; cloud sync needs server setup.'))},[]);
 useEffect(()=>{localStorage.setItem(STORAGE,JSON.stringify({owned,saved}));if(account)syncCloud({owned,saved}).catch(()=>{})},[owned,saved,account]);
 const filtered=useMemo(()=>cards.filter(c=>(rarity==='All'||c.rarity===rarity)&&c.name.toLowerCase().includes(query.toLowerCase())),[cards,rarity,query]);
 const stats=analyze(deck),ai=analyzeDeckAI(deck),weaknesses=findDeckWeaknesses(deck),matchups=analyzeMatchups(deck,opponent),replacements=suggestReplacements(deck,cards,owned,style);
 const avg=deck.length?(deck.reduce((s,c)=>s+c.elixir,0)/deck.length).toFixed(1):'0.0';
 const toggle=id=>setOwned(o=>({...o,[id]:{...(o[id]||{}),max:!o[id]?.max,level:!o[id]?.max?16:(o[id]?.level||1)}}));
 const add=c=>{if(deck.length>=8)return setNotice('دک کامل است.');if(deck.some(x=>x.id===c.id))return setNotice('این کارت داخل دک است.');setDeck(d=>[...d,c])};
 const gen=()=>{setDeck(generateDeckAI(cards,owned,style));setNotice(Object.values(owned).filter(x=>x.max).length>=8?'دک از کارت‌های MAX شما ساخته شد.':'برای شخصی‌سازی دقیق، حداقل ۸ کارت را MAX کنید.')};
 const copy=async()=>{if(deck.length!==8)return setNotice('ابتدا ۸ کارت انتخاب کن.');const l=link(deck);if(!l)return setNotice('یکی از کارت‌های این دک ID رسمی Clash Royale ندارد.');try{await navigator.clipboard.writeText(l);setNotice('لینک Deck کپی شد.')}catch{setNotice(l)}};
 const open=()=>{if(deck.length!==8)return setNotice('دک باید ۸ کارت داشته باشد.');const l=link(deck);if(!l)return setNotice('یکی از کارت‌های این دک ID رسمی Clash Royale ندارد.');window.location.href=l};
 const submitAuth=async()=>{try{setAccountNotice('Connecting…');const a=authMode==='login'?await loginAccount(authEmail,authPassword):await registerAccount(authName,authEmail,authPassword);setAccount(a);const d=await loadCloud();setOwned(d.owned||{});setSaved(d.saved||[]);localStorage.setItem(STORAGE,JSON.stringify({owned:d.owned||{},saved:d.saved||[]}));setAuthMode('login');setAuthPassword('');setAccountNotice('Cloud account connected and data synced.')}catch(e){setAccountNotice(e.message)}};
 const save=()=>{if(deck.length!==8)return setNotice('دک ۸ کارتی را ذخیره کن.');setSaved(s=>[{id:Date.now(),style,avg,ids:deck.map(c=>c.id)},...s].slice(0,20));setNotice('ذخیره شد.')};
 return <div className="app"><header><div className="brand"><div className="logo">SD</div><div><h1>Special Deck</h1><p>Smart Clash Royale Deck Builder</p></div></div><div className="header-actions"><button className="ghost" onClick={()=>setTab('collection')}>My Collection</button><button className="ghost" onClick={()=>setTab('account')}>{account?`👤 ${account.name}`:'👤 Account'}</button><button className="primary" onClick={gen}>✨ Generate Deck</button></div></header>
 <main><section className="hero"><div><span className="pill">SPECIAL DECK V8</span><h2>Build smarter decks from <em>your real collection.</em></h2><p>کارت‌های خودت را مشخص کن، سطح آن‌ها را تنظیم کن و Special Deck یک دک ۸ کارتی متناسب با سبک انتخابی‌ات می‌سازد.</p></div><div className="hero-orb">⚔️<small>8 CARDS</small></div></section>
 <div className="toolbar"><div className="tabs"><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}>Builder</button><button className={tab==='collection'?'active':''} onClick={()=>setTab('collection')}>My Collection</button><button className={tab==='saved'?'active':''} onClick={()=>setTab('saved')}>Saved Decks</button><button className={tab==='meta'?'active':''} onClick={()=>setTab('meta')}>Meta Decks</button></div><select value={style} onChange={e=>setStyle(e.target.value)}><option>Balanced</option><option>Cycle</option><option>Control</option><option>Beatdown</option><option>BridgeSpam</option></select></div>
 <section className="workspace"><div className="panel deck-panel"><div className="panel-head"><div><h3>Your Deck</h3><span>{deck.length}/8 cards</span></div><div className="elixir">⚡ {avg}</div></div><div className="deck-grid">{deck.map(c=><div className="deck-card" key={c.id}><div className="card-art"><b>{initials(c.name)}</b><span>{c.elixir}⚡</span></div><div className="card-name">{c.name}</div><button onClick={()=>setDeck(d=>d.filter(x=>x.id!==c.id))}>×</button></div>)}{Array.from({length:8-deck.length}).map((_,i)=><div className="empty-slot" key={i}>+</div>)}</div><div className="deck-actions"><button className="primary" onClick={copy}>📋 Copy Deck</button><button className="secondary" onClick={open}>⚔️ Open Clash Royale</button><button className="secondary" onClick={save}>💾 Save</button><button className="danger" onClick={()=>setDeck([])}>Clear</button></div>{notice&&<div className="notice">{notice}</div>}</div>
 <aside className="panel analysis"><h3>Deck Analysis</h3><Metric name="Attack" value={stats.attack}/><Metric name="Defense" value={stats.defense}/><Metric name="Air Defense" value={stats.air}/><Metric name="Cycle" value={stats.cycle}/><Metric name="Synergy" value={ai.synergy}/><Metric name="Coverage" value={ai.coverage}/><div className="analysis-row"><span>Win Conditions</span><b>{stats.wins}</b></div><div className="analysis-row"><span>Spells</span><b>{stats.spells}</b></div><div className="analysis-row"><span>AI Score</span><b>{ai.score}/100</b></div><div className="tips"><b>Special Deck Insight</b><p>{deck.length<8?'Complete 8 cards for a full analysis.':weaknesses[0]?.detail||'Role coverage looks balanced. Test the deck in your preferred mode.'}</p></div><div className="matchup-box"><h4>Counter Check</h4><p>Opponent cards selected: {opponent.length}</p><b>{matchups.score}/100 coverage</b></div><div className="replacement-box"><h4>Suggested Fixes</h4>{replacements.slice(0,3).map(x=><button key={x.weakness.key} onClick={()=>{setDeck(d=>d.length?d.map((c,i)=>i===d.length-1?x.replacement:c):d);setNotice(`Suggested replacement: ${x.replacement.name}`)}}>{x.weakness.title} → {x.replacement.name}</button>)}</div></aside></section>
 <section className="panel opponent"><div className="panel-head"><div><h3>Opponent / Counter Lab</h3><span>Select enemy cards to test matchup coverage.</span></div><button className="secondary" onClick={()=>setOpponent([])}>Clear</button></div><div className="card-list">{cards.slice(0,60).map(c=><button key={c.id} className={`enemy-chip ${opponent.some(x=>x.id===c.id)?'selected':''}`} onClick={()=>setOpponent(o=>o.some(x=>x.id===c.id)?o.filter(x=>x.id!==c.id):[...o,c])}>{c.name}</button>)}</div></section>
 <section className="panel collection">{(()=>{
  if(tab==='account')return (<><div className="panel-head"><div><h3>👤 My Account</h3><span>Cloud profile and synced collection</span></div></div>{account?<div className="account-card"><div className="profile-avatar">{initials(account.name)}</div><div className="account-info"><h3>{account.name}</h3><p>{account.email}</p></div><button className="danger" onClick={()=>{logoutAccount();setAccount(null);setAccountNotice('Signed out.')}}>Sign out</button></div>:<div className="auth-box"><div className="auth-tabs"><button className={authMode==='login'?'active':''} onClick={()=>setAuthMode('login')}>Login</button><button className={authMode==='register'?'active':''} onClick={()=>setAuthMode('register')}>Create account</button></div>{authMode==='register'&&<input value={authName} onChange={e=>setAuthName(e.target.value)} placeholder="Your name"/>}<input value={authEmail} onChange={e=>setAuthEmail(e.target.value)} placeholder="Email" type="email"/><input value={authPassword} onChange={e=>setAuthPassword(e.target.value)} placeholder="Password (8+ characters)" type="password"/><button className="primary" onClick={submitAuth}>{authMode==='login'?'Login':'Create account'}</button></div>}{accountNotice&&<div className="notice">{accountNotice}</div>}</>);
  if(tab==='meta')return (<><div className="panel-head"><div><h3>Meta Decks</h3><span>Current saved meta snapshot</span></div></div><div className="meta-grid">{META_DECKS.map(m=><div className="meta-card" key={m.key}><h4>{m.name}</h4><span>{m.archetype}</span><b>{m.winRate}% WR</b><div className="meta-cards">{m.cards.map(n=><span key={n}>{n}</span>)}</div><button className="primary" onClick={()=>{const d=resolveMetaDeck(m,cards);if(d.length===8){setDeck(d);setTab('builder');setNotice(`${m.name} loaded.`)}else setNotice('Some cards are not in the current database.')}}>Load Deck</button></div>)}</div></>);
  if(tab==='saved')return (<><div className="panel-head"><div><h3>Saved Decks</h3><span>{saved.length} saved</span></div></div><div className="saved-list">{saved.length?saved.map(x=><button key={x.id} onClick={()=>{const d=x.ids.map(id=>cards.find(c=>c.id===id)).filter(Boolean);if(d.length===8)setDeck(d)}}>⚔️ {x.style} • {x.avg} elixir • Load</button>):<div className="loading">No saved decks yet.</div>}</div></>);
  return (<><div className="panel-head"><div><h3>{tab==='collection'?'My Card Collection':'Card Database'}</h3><span>{cards.length} cards • Max Level 16</span></div><div className="search"><input placeholder="Search cards..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="collection-summary"><b>{Object.values(owned).filter(x=>x.max).length}</b><span>MAX cards</span><b>{Object.values(owned).filter(x=>x.level).length}</b><span>tracked cards</span></div><div className="filters"><button className={rarity==='All'?'sel':''} onClick={()=>setRarity('All')}>All</button>{['Common','Rare','Epic','Legendary','Champion'].map(r=><button key={r} className={rarity===r?'sel':''} onClick={()=>setRarity(r)}>{r}</button>)}</div><div className="card-list">{filtered.map(c=><div className={`card-tile ${owned[c.id]?.max?'owned':''}`} key={c.id}><button className="card-main" onClick={()=>add(c)}><div className="tile-art"><span>{initials(c.name)}</span><i>{c.elixir}⚡</i></div><b>{c.name}</b><small>{c.rarity} • {c.type}{c.evolution?' • EVO':''}{c.hero?' • HERO':''}</small></button><button className="max-btn" onClick={()=>toggle(c.id)}>{owned[c.id]?.max?'MAX ✓':'Set MAX'}</button></div>)}</div></>);
})()}</section></main><footer>Special Deck is a fan-made web tool. Clash Royale and Supercell are trademarks of Supercell.</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
