import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {loadCards} from './data/cards';
import './style.css';

const roleMap={
  'Hog Rider':'Win Condition','Giant':'Win Condition','Royal Giant':'Win Condition','Balloon':'Win Condition','Wall Breakers':'Win Condition','Royal Hogs':'Win Condition','Goblin Barrel':'Win Condition','X-Bow':'Win Condition','Mortar':'Win Condition','Ram Rider':'Win Condition','Goblin Giant':'Win Condition','P.E.K.K.A':'Tank Killer','Mega Knight':'Tank / Defense','Knight':'Mini Tank','Archers':'Air Defense','Minions':'Air Defense','Hunter':'Air Defense','Magic Archer':'Support','Ice Wizard':'Control','Fireball':'Medium Spell','The Log':'Small Spell','Zap':'Small Spell','Poison':'Control Spell','Tornado':'Control Spell','Cannon':'Building','Tesla':'Building','Inferno Tower':'Building','Bomb Tower':'Building','Elixir Collector':'Economy'};
const styleWeights={Balanced:{win:1.0,def:1.0,cycle:1.0,air:1.0},Cycle:{win:1.1,def:1.0,cycle:1.45,air:.9},Control:{win:1.1,def:1.35,cycle:1.0,air:1.15},Beatdown:{win:1.35,def:1.0,cycle:.7,air:1.1},BridgeSpam:{win:1.25,def:1.0,cycle:1.1,air:1.0}};
function initials(n){return n.split(/\s+/).map(x=>x[0]).slice(0,2).join('')}
function cardScore(c,owned,style){let s=0; const role=roleMap[c.name]||''; if(role.includes('Win'))s+=6*styleWeights[style].win; if(role.includes('Defense')||role.includes('Building')||role.includes('Tank'))s+=4*styleWeights[style].def; if(c.elixir<=3)s+=3*styleWeights[style].cycle; if(['Air Defense','Support'].includes(role))s+=2.5*styleWeights[style].air; if(owned.has(c.id))s+=3; s+=Math.max(0,4-c.elixir)*.5; return s}
function generateDeck(cards,owned,style){
  const sorted=[...cards].sort((a,b)=>cardScore(b,owned,style)-cardScore(a,owned,style));
  const out=[]; const hasRole=r=>out.some(c=>(roleMap[c.name]||'').includes(r));
  for(const c of sorted){if(out.length>=8)break; if(out.some(x=>x.id===c.id))continue; const role=roleMap[c.name]||''; if(role.includes('Win')&&!hasRole('Win'))out.push(c); else if(role.includes('Building')&&!hasRole('Building'))out.push(c); else if(role.includes('Spell')&&out.filter(x=>(roleMap[x.name]||'').includes('Spell')).length<2)out.push(c); else if(role.includes('Defense')&&!out.some(x=>(roleMap[x.name]||'').includes('Defense')))out.push(c); else if(!out.some(x=>x.elixir===c.elixir&&x.elixir>=6)||c.elixir<6)out.push(c)}
  return out.length===8?out:sorted.slice(0,8);
}
function DeckCard({card,onRemove,selected}){return <div className={`deck-card ${selected?'selected':''}`}><div className="card-art"><b>{initials(card.name)}</b><span>{card.elixir}⚡</span></div><div className="card-name">{card.name}</div><button onClick={()=>onRemove(card)}>×</button></div>}
function App(){
 const [cards,setCards]=useState([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [rarity,setRarity]=useState('All'); const [owned,setOwned]=useState(new Set()); const [deck,setDeck]=useState([]); const [style,setStyle]=useState('Balanced'); const [tab,setTab]=useState('builder'); const [notice,setNotice]=useState('');
 useEffect(()=>{loadCards().then(x=>{setCards(x);setLoading(false)})},[]);
 const filtered=useMemo(()=>cards.filter(c=>(rarity==='All'||c.rarity===rarity)&&c.name.toLowerCase().includes(query.toLowerCase())),[cards,rarity,query]);
 const avg=deck.length?(deck.reduce((s,c)=>s+c.elixir,0)/deck.length).toFixed(1):'0.0';
 const stats=useMemo(()=>{let attack=0,def=0,air=0,cycle=0; deck.forEach(c=>{const r=roleMap[c.name]||''; if(r.includes('Win'))attack+=18;if(r.includes('Support'))attack+=7;if(r.includes('Defense')||r.includes('Building')||r.includes('Tank'))def+=15;if(r.includes('Air'))air+=20;if(c.elixir<=3)cycle+=14});return {attack:Math.min(100,attack),def:Math.min(100,def),air:Math.min(100,air),cycle:Math.min(100,cycle)}} ,[deck]);
 const add=c=>{if(deck.length>=8){setNotice('دک کامل است.');return} if(deck.some(x=>x.id===c.id)){setNotice('این کارت قبلاً در دک است.');return}setDeck([...deck,c]);setNotice('')};
 const remove=c=>setDeck(deck.filter(x=>x.id!==c.id));
 const generate=()=>{setDeck(generateDeck(cards,owned,style));setNotice('دک جدید ساخته شد.')};
 const copy=async()=>{if(deck.length!==8){setNotice('ابتدا ۸ کارت انتخاب کن.');return} const ids=deck.map(c=>c.id).join(';'); const inbox=`clashroyale-inbox://copyDeck?deck=${ids}`; try{await navigator.clipboard.writeText(inbox);setNotice('لینک دک کپی شد؛ حالا آن را در Clash Royale باز کن.')}catch{setNotice(inbox)}};
 const openCR=()=>{if(deck.length!==8){setNotice('ابتدا ۸ کارت انتخاب کن.');return} const ids=deck.map(c=>c.id).join(';');window.location.href=`clashroyale://copyDeck?deck=${ids}`};
 return <div className="app"><header><div className="brand"><div className="logo">SD</div><div><h1>Special Deck</h1><p>Smart Clash Royale Deck Builder</p></div></div><div className="header-actions"><button className="ghost" onClick={()=>setTab('builder')}>Deck Builder</button><button className="primary" onClick={generate}>✨ Generate Deck</button></div></header>
 <main><section className="hero"><div><span className="pill">PRO DECK ENGINE</span><h2>Build a deck around your <em>maxed cards.</em></h2><p>Choose the cards you own, pick a playstyle, and Special Deck builds an 8-card deck with balance checks and Clash Royale copy support.</p></div><div className="hero-orb">⚔️<small>8 CARDS</small></div></section>
 <div className="toolbar"><div className="tabs"><button className={tab==='builder'?'active':''} onClick={()=>setTab('builder')}>Builder</button><button className={tab==='collection'?'active':''} onClick={()=>setTab('collection')}>My Collection</button></div><select value={style} onChange={e=>setStyle(e.target.value)}><option>Balanced</option><option>Cycle</option><option>Control</option><option>Beatdown</option><option>BridgeSpam</option></select></div>
 <section className="workspace"><div className="panel deck-panel"><div className="panel-head"><div><h3>Your Deck</h3><span>{deck.length}/8 cards</span></div><div className="elixir">⚡ {avg}</div></div><div className="deck-grid">{deck.map(c=><DeckCard key={c.id} card={c} onRemove={remove}/>) }{Array.from({length:8-deck.length}).map((_,i)=><div className="empty-slot" key={i}>+</div>)}</div><div className="deck-actions"><button className="primary" onClick={copy}>📋 Copy Deck</button><button className="secondary" onClick={openCR}>⚔️ Open Clash Royale</button><button className="danger" onClick={()=>setDeck([])}>Clear</button></div>{notice&&<div className="notice">{notice}</div>}</div>
 <aside className="panel analysis"><h3>Deck Analysis</h3><Metric name="Attack" value={stats.attack}/><Metric name="Defense" value={stats.def}/><Metric name="Air Defense" value={stats.air}/><Metric name="Cycle" value={stats.cycle}/><div className="tips"><b>Pro check</b><p>{deck.length<8?'Complete the deck to run a full analysis.':avg>4.2?'High average elixir — consider adding a cheaper cycle card.':stats.air<35?'Air defense is light — add a reliable anti-air card.':stats.def<40?'Defense is thin — consider a building or defensive support.':'The deck has a balanced role mix. Test it in your preferred mode.'}</p></div></aside></section>
 <section className="panel collection"><div className="panel-head"><div><h3>{tab==='collection'?'My Card Collection':'Choose Cards'}</h3><span>{cards.length} cards available</span></div><div className="search"><input placeholder="Search cards..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="filters"><button className={rarity==='All'?'sel':''} onClick={()=>setRarity('All')}>All</button>{['Common','Rare','Epic','Legendary','Champion'].map(r=><button key={r} className={rarity===r?'sel':''} onClick={()=>setRarity(r)}>{r}</button>)}</div><div className="card-list">{loading?<div className="loading">Loading card database…</div>:filtered.slice(0,120).map(c=><button className={`card-tile ${owned.has(c.id)?'owned':''}`} key={c.id} onClick={()=>add(c)}><div className="tile-art"><span>{initials(c.name)}</span><i>{c.elixir}⚡</i></div><b>{c.name}</b><small>{c.rarity}</small><label onClick={e=>{e.stopPropagation();setOwned(new Set(owned.has(c.id)?[...owned].filter(x=>x!==c.id):[...owned,c.id]))}}>{owned.has(c.id)?'MAX ✓':'Set MAX'}</label></button>)}</div></section>
 </main><footer>Special Deck • Independent fan-made deck builder • Clash Royale and Supercell are trademarks of Supercell. Data source fallback powered by community-maintained card constants.</footer></div>}
function Metric({name,value}){return <div className="metric"><div><span>{name}</span><b>{value}</b></div><div className="bar"><i style={{width:`${value}%`}}/></div></div>}

createRoot(document.getElementById('root')).render(<App/>);
